name = "deltadefi-protocol/khor"
version = "0.0.0"
compiler = "v1.1.17"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken contracts for project 'deltadefi-protocol/khor'"

[repository]
user = "deltadefi-protocol"
project = "khor"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v1.9.1"
source = "github"

[config]
